
[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2024"
name = "perception_audio_recorder"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4"
cpal = "0.17.1"
crossbeam-channel = "0.5.15"
hound = "3.5.1"
mp3lame-encoder = "0.2.2"
rubato = "=0.14.1"   # 注意前面的等号
ringbuf = "=0.3.3"   # 注意前面的等号
napi = "3.0.0"
napi-derive = "3.0.0"
webrtc-audio-processing = { version = "0.4.0", optional = true, features = ["bundled"] }
nnnoiseless = "=0.2.1"

[features]
default = []
webrtc_apm = ["webrtc-audio-processing"]

[dependencies.windows]
version = "0.62.2"
features = ["Win32_Foundation","Win32_System_Threading","Win32_UI_WindowsAndMessaging"]

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
