/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function doInitialize(log: ((err: Error | null, arg: string) => any)): void

export declare function getRecordDuration(): number

export declare function isPaused(): boolean

export declare function isRecording(): boolean

export declare function listenPauseRecordingAudio(listener: ((err: Error | null, ) => any)): void

export declare function listenRecordingError(listener: ((err: Error | null, arg: RecordingErrorInfo) => any)): void

export declare function listenRecordingProgress(listener: ((err: Error | null, arg: RecordingProgressInfo) => any)): void

export declare function listenResumeRecordingAudio(listener: ((err: Error | null, ) => any)): void

export declare function listenStartRecordingAudio(listener: ((err: Error | null, ) => any)): void

export declare function listenStopRecordingAudio(listener: ((err: Error | null, ) => any)): void

export declare function pauseRecording(): void

export interface RecordingErrorInfo {
  errorType: string
  errorMessage: string
  errorCode: number
  occurredAt: string
}

export interface RecordingProgressInfo {
  totalDuration: number
  buffer: Float32Array
  micBuffer: Float32Array
  spkBuffer: Float32Array
  totalSize: number
}

export declare function resumeRecording(): void

export declare function startRecording(saveDir?: string | undefined | null, recordDevice?: number | undefined | null, sampleRate?: number | undefined | null, channels?: string | undefined | null, saveToFile?: boolean | undefined | null): void

export declare function stopRecording(): void
